config/routes.rb
TheChildrensJourney::Application.routes.draw do
  
  root :to => 'pages#home', :as => 'home'

  get 'about' => "pages#about"

  get 'enrollment' => "pages#enrollment"

  get 'location' => "pages#location"

  get 'handbook' => "pages#handbook"

  get 'contact' => "pages#contact"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def enrollment
  end

  def location
  end

  def handbook
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def link_to_with_current_class(name, options)
      if current_page?(options)
      content_tag :li, link_to(h(name), options), :class => "current"
    else
      content_tag :li, link_to(h(name), options)
    end   
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Children's Journey | Day Care</title>
  <meta name="description" content="The Children’s Journey is a ministry of the Journey Fellowship. We are a non-profit, non-discriminatory, service organization.">
  <meta property="og:url" content="http://www.thechildrensjourney.org" />
  <meta property="og:type" content="website" />
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script type="text/javascript">
    // global variables 
    var compareWidth, //previous width used for comparison
    	detector, //the element used to compare changes
    	smallScreen; // Size of maximum width of single column media query
    jQuery(document).ready(function(){
        //set the initial values
        detector = jQuery('.js');
        compareWidth = detector.width();
    	smallScreen = '820'; 
    	if ($(window).width() < smallScreen) {
    		$("body").addClass("one-column");		
    	}
    	else {
    		$("body").addClass("two-column");	
    	}
    	// Toggle for nav menu
    	$('.js .menu-button').click(function() {
    	  $(this).toggleClass('expanded');
    		$('[role="navigation"]').slideToggle('fast', function() {});			
    	});	
    	// Credit: http://webdeveloper2.com/2011/06/trigger-javascript-on-css3-media-query-change/
        jQuery(window).resize(function(){
            //compare everytime the window resize event fires
            if(detector.width()!=compareWidth){
                //a change has occurred so update the comparison variable
                compareWidth = detector.width();
    			if (compareWidth < smallScreen) {
    				$("body").removeClass("two-column").addClass("one-column");				
    			}
    			else {
    				$("body").removeClass("one-column").addClass("two-column");	
    			}
    			if (compareWidth >= smallScreen) {
    				$('[role="navigation"]').show();
    			}
            }
        });
     });
  </script>
</head>
<body>
  <header>
    <div class="header">
      <div class="navBar"></div>
      <div class="container logoContainer">
        <div class="logo">
          <h1>
            <a href="/">
              The Children's Journey
            </a>
          </h1>
        </div>
      </div>
      <nav>
        <div class="navContainer container">
          <div class='menu-button'></div>	
          <ul id="nav" role="navigation">
            <%= link_to_with_current_class "Home", home_path %><%= link_to_with_current_class "About", about_path %><%= link_to_with_current_class "Enrollment", enrollment_path %><%= link_to_with_current_class "Location", location_path %><%= link_to_with_current_class "Handbook", handbook_path %><%= link_to_with_current_class "Contact", contact_path %>
          </ul>
        </nav>
    </div>
  </header>
  </div>

<%= yield %>

<footer>
<ul class="footerNav">
  <%= link_to_with_current_class "Home", home_path %>
  |
  <%= link_to_with_current_class "About", about_path %>
  |
  <%= link_to_with_current_class "Enrollment", enrollment_path %>
  |
  <%= link_to_with_current_class "Location", location_path %>
  |
  <%= link_to_with_current_class "Handbook", handbook_path %>
  |
  <%= link_to_with_current_class "Contact", contact_path %>
</ul>
<p>Copyright © 2012 Children's Journey. All rights reserved.</p>
</footer>

</body>
</html>

app/views/pages/_sidebar.html.erb
 <div class="sidebar classroom">
    <h2>
      Classrooms
    </h2>
    <ul>
      <li>
        Infants
      </li>
      <li>
        Toddlers
      </li>
      <li>
        Preschool/Pre-Kindergarten
      </li>
      <li>
        School Age
      </li>
    </ul>
  </div><!--End Sidebar-->
  <div class="sidebar address">
    <h2>
      Address
    </h2>
    <p>
      600 Alton Ave.<br/>
      Reading, PA 19605<br/>
      610-334-8741
      </p>
  </div><!--End Sidebar-->
  <div class="sidebar hours">
    <h2>
      Hours
    </h2>
    <p>
      Monday-Friday<br/>
      6:30am - 6:00pm
      </p>
  </div><!--End Sidebar-->

app/views/pages/about.html.erb
<div class="mainImage">
  <div class="container">
    <img src="/images/about_photo.jpg" alt="Home Image">
  </div>
</div>
<div class="sectionDivider"></div>
<div class="container">
  <div class="allContent">
    <div class="mainContent">
      <article>
        <div class="sectionContent mainHeader">
          <h1>About Us</h1>
        </div>
        <div class="sectionContent">
          <img src="/images/objectives.jpg" alt="Objectives">
        </div>
      </article>
    </div>
   
   <%= render '/pages/sidebar' %>
  
  </div>
</div>

app/views/pages/contact.html.erb
<div class="mainImage">
  <div class="container">
    <img src="/images/contact_photo.jpg" alt="Home Image">
  </div>
</div>
<div class="sectionDivider"></div>
<div class="container">
  <div class="allContent">
    <div class="mainContent">
      <article>
        <div class="sectionContent mainHeader">
          <h1>Contact Us</h1>
        </div>
        <div class="sectionContent">
          <p>Feel Free to Contact Us with any questions, comments, or concerns.</p>
          <p>
            <strong>The Children's Journey</strong><br>
              Phone: <a href="tel:6109210770">610-921-0770</a><br>
          </p>
          <p>
            <strong>Brydie Harris - Lead Pastor</strong><br>
                    Phone: <a href="tel:610-334-8741">610-334-8741</a><br>
                    Email: <a href="mailto:journeyfellowship@msn.com">journeyfellowship@msn.com</a><br>
          </p>

         
        </div>
      </article>
    </div>
   
   <%= render '/pages/sidebar' %>
  
  </div>
</div>

app/views/pages/enrollment.html.erb
<div class="mainImage">
  <div class="container">
    <img src="/images/enrollment_photo.jpg" alt="Home Image">
  </div>
</div>
<div class="sectionDivider"></div>
<div class="container">
  <div class="allContent">
    <div class="mainContent">
      <article>
        <div class="sectionContent mainHeader">
          <h1>Enrollment Polices and Procedures</h1>
        </div>
        <div class="sectionContent">
          <p>
            Children are granted enrollment on a non-discriminatory basis without regard to sex, race, color, religion, creed, political belief or national origin. Enrollment is open to all children, provided the center can meet the needs of the child. We are not staffed to provide one-on-one care.
          </p>
          <p>
            All new enrollees will be subject to a three-week probationary period. A child should be enrolled no less than 1 day prior to his or her first day of attendance. As part of the enrollment process, the following forms must be completed and submitted to the office prior to the first day of attendance (unless otherwise noted) 
          </p>
        </div>
        <div class="sectionContent">
          <h1>Enrollment Forms</h1>
        </div>
        <div class="sectionContent">
          <p class="subText">
            Click on the forms below to view and print.
          </p>
          <ol>
            <li><a href="/assets/enrollmentforms/Emergency Contact Form.pdf" target="_blank">Registration / Emergency Contact Form</a></li>
            <li><a href="/assets/parenthandbook12192009.pdf" target="_blank">Parent Handbook</a></li>
           <li><a href="/assets/enrollmentforms/Child Health Report.pdf" target="_blank">Child Health Assessment Form</a><span class="subText">(this is required no later than 30 days after enrollment date)</span></li>
           <li><a href="/assets/enrollmentforms/SUNSCREEN CONSENT FORM.docx" target="_blank">Sun Block Permission Form</a></li>
           <li><a href="/assets/enrollmentforms/PhotographReleaseForm 01162011.doc" target="_blank">Permission to Photograph Form</a></li>
           <li><a href="/assets/enrollmentforms/CACFP MealBenefit Form.pdf" target="_blank">Meal Benefit Application</a></li>
          </ol>
          <p class="subText">
            *All Forms are available upon request in the school office.
          </p>
          <p>As part of the enrollment process,  the following payments must also be submitted to the office prior to the first day of attendance.</p>
          <ol>
            <li>
              **Non-refundable Registration Fee
            </li>
            <li>
              **Tuition Deposit
            </li>
          </ol>
        </div>
      </article>
    </div>
   
   <%= render '/pages/sidebar' %>
  
  </div>
</div>

app/views/pages/handbook.html.erb
<div class="mainImage">
  <div class="container">
    <img src="/images/handbook_photo.jpg" alt="Home Image">
  </div>
</div>
<div class="sectionDivider"></div>
<div class="container">
  <div class="allContent">
    <div class="mainContent">
      <article>
        <div class="sectionContent mainHeader">
          <h1>Parent Handbook</h1>
        </div>
        <div class="sectionContent">
          <div align="center"><img src="/images/handbook_img.png" width="139" height="153"></div>
          
          <h2>WELCOME!!</h2>

          <p>Welcome to the Children's Journey!  We are grateful that you have entrusted your child to our care.  We look forward to being a part of your child's growth, development and early education. Thank you for allowing us to be a part of this wonderful process! The Children's Journey is a ministry of the Journey Fellowship. We are a non-profit, non-discriminatory, service organization.</p>
          <p><a href="/assets/parenthandbook12192009.pdf" target="_blank">View More...</a></p>
         
        </div>
      </article>
    </div>
   
   <%= render '/pages/sidebar' %>
  
  </div>
</div>

app/views/pages/home.html.erb
<div class="mainImage">
  <div class="container">
    <img src="/images/home_photo.jpg" alt="Home Image">
    <div class="imageMessage">
      <p>
        “It is our desire to love and care for the families and the children entrusted to us, as Jesus does, with all our passion, soul, mind, and strength."
      </p>
    </div>
  </div>
</div>
<div class="sectionDivider"></div>
<div class="container">
  <div class="allContent">
    <div class="mainContent">
      <article>
        <div class="sectionContent mainHeader">
          <h1>Welcome to The Children's Journey</h1>
        </div>
        <div class="sectionContent">
          <p>The Children’s Journey is a ministry of the Journey Fellowship. We are a non-profit, non-discriminatory, service organization. We are licensed and certified by the PA Dept of Welfare and comply with all standards set forth by that department.</p>
        </div>
      </article>
      <br/>
      <article>
        <div class="sectionContent">
          <h1>What's Happening?</h1>
        </div>
        <div class="feed">
          <script src="http://feeds.feedburner.com/blogspot/CWTyL?format=sigpro" type="text/javascript" ></script><noscript><p>Subscribe to RSS headline updates from: <a href="http://feeds.feedburner.com/blogspot/CWTyL"></a></p> </noscript>
        </div>
      </article>
    </div>
   
   <%= render '/pages/sidebar' %>
  
  </div>
</div>

app/views/pages/location.html.erb
<div class="mainImage">
  <div class="container">
    <img src="/images/location_photo.jpg" alt="Home Image">
  </div>
</div>
<div class="sectionDivider"></div>
<div class="container">
  <div class="allContent">
    <div class="mainContent">
      <article>
        <div class="sectionContent mainHeader">
          <h1>Location</h1>
        </div>
        <div class="sectionContent">
         <iframe width="425" scrolling="no" height="350" frameborder="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=600+Alton+Avenue,+Reading,+PA&amp;sll=37.0625,-95.677068&amp;sspn=68.344727,177.451172&amp;ie=UTF8&amp;hq=&amp;hnear=600+Alton+Ave,+Reading,+Berks,+Pennsylvania+19605&amp;z=14&amp;ll=40.366284,-75.923762&amp;output=embed" marginwidth="0" marginheight="0"></iframe><br><small><a style="color:#C77E0C; text-align:left" href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=600+Alton+Avenue,+Reading,+PA&amp;sll=37.0625,-95.677068&amp;sspn=68.344727,177.451172&amp;ie=UTF8&amp;hq=&amp;hnear=600+Alton+Ave,+Reading,+Berks,+Pennsylvania+19605&amp;z=14&amp;ll=40.366284,-75.923762" target="_blank">View Larger Map</a></small>
        </div>
      </article>
    </div>
   
   <%= render '/pages/sidebar' %>
  
  </div>
</div>